newBikes = //span[text()='NEW BIKES']
upcomingBikes = Upcoming Bikes
hondaBrand = //a[text() = 'Honda']
under5Lakhs = //a[contains(@title,'Upcoming Bikes Under 5 Lakhs')]
bikeList = //li[contains(@class,'modelItem')]


moreMenu = //span[text()='MORE']
usedCars = Used Cars
location = //a[@title='Chennai']
popularModel = //div[text()='Popular Models']
checkBoxList = //input[@class='carmmCheck' and @type='checkbox']
carList = //*[contains(@class,'pl-30')]


loginIcon = //div[@id='des_lIcon']
googleBtn = //span[.='Google']
checkWindowIsOpened = (//div[.='Sign in with Google'])[3]
windowHeading = //h1
chooseAnAccount = //div[@class='riDSKb']
emailField = //input[@id='identifierId']
nextBtn = //span[text()='Next']
errorMsg = //div/span[@class='AfGCob']
